//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXP_TRACKER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalExpenseLimit
    {
        public int TotalExpenseId { get; set; }
        public int TotalExpenseLimit1 { get; set; }
    }
}
